version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web
  web:
    container_name: web
    build: ./app
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pg_admin
      - POSTGRES_PASSWORD=pgadm123
      - POSTGRES_DB=postgresql

volumes:
  postgres_data:
  static_volume:

