# Generated by Django 5.0.6 on 2024-11-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('chat', '0001_initial'),
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.game'),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.friendrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='game_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.game'),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamenthistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamenthistory',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.tournament'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user2', 'user1'), name='inverse_unique_friendship'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2'), ('user2', 'user1')},
        ),
    ]
