{
 "title": "ft_transcendence",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "User List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM api_user_site" }
   ]
  },
  {
   "title": "Game List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM api_matchhistory" }
   ]
  },
  {
   "title": "Django Responses by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "project_django_http_requests_total_by_method_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django DB Querys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "project_django_db_execute_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": ".ds-metrics-nginx",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Django Live",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "10000" }, "type": "logs" }
     ],
     "query": "django-logs",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PostgreSQL Live",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "10000" }, "type": "logs" }
     ],
     "query": "postgresql-logs",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}