global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - backend-alertmanager:9093
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['backend-prometheus:9090']

  - job_name: "django"
    scrape_interval: 10s
    static_configs:
      - targets: ['backend-django:8000']