global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets: ['backend-alertmanager:9093']
      tls_config:
        insecure_skip_verify: true

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scheme: https
    static_configs:
    - targets: ['backend-prometheus:9090']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'grafana'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['backend-grafana:3000']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'django'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: [ 'backend-django:8000' ]
    tls_config:
      insecure_skip_verify: true

  - job_name: 'elasticsearch'
    scrape_interval: 10s
    scheme: https
    metrics_path: '/_prometheus/metrics'
    basic_auth:
      username: "elastic"
      password: "transcendence"
    static_configs:
      - targets: ['backend-elastic:9200']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'frontend'
    scrape_interval: 10s
    static_configs:
    - targets: ['export-frontend:9113']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'proxy'
    scrape_interval: 10s
    static_configs:
    - targets: ['export-proxy:9113']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'postgresql'
    scrape_interval: 10s
    static_configs:
    - targets: ['export-postgresql:9187']
    tls_config:
        insecure_skip_verify: true