global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: https
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets: ['backend-alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scheme: https
    static_configs:
    - targets: ['backend-prometheus:9090']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'grafana'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['backend-grafana:3000']
    tls_config:
        insecure_skip_verify: true

  - job_name: 'django'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend-django:8000']

#  - job_name: 'postgres'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['backend-postgresql:5432']